# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

target 'livre' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Filling
    pod 'RxSwift', '6.0.0'
    pod 'RxCocoa', '6.0.0'
    pod 'Alamofire', '~> 5.2'
    pod 'lottie-ios'
    pod 'Then'

end
